### ISSUE TITLE
[Problem] Pokemon Black 2 Japan Code Generating error

### ISSUE THREAD

**Issue by the4anoni** [Prof9/wfcreplay#17]
When I generating code for Black 2 J it shows error:
''FATAL ERROR: Could not find a suitable code cave.''
I use WfcReplay 0.5.

**Comment by Prof9** [comment]
Unfortunately it seems despite my optimizations, Pokémon Black 2 (J) still requires a bigger code cave than what's available. I've added some extra functionality to detect such problem games and use two code caves if necessary in commit 3a0c4db. Could you try the following code and see if it works for you?

```
::Bypass HTTPS v0.6 for [IREJ] POKEMON B2 RevA
5207C4CC EE070F90
E2004310 0000003C
CA024A0D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
020044C8 00000000
E20044C8 00000042
D2E91A79 000A002C
00A70009 D2EB004D
001D87AD 00190018
00190019 00190019
001A001A 0005052A
01644AAF 00130016
01BE0016 00120015
00140013 001D0012
00000000 00000000
0207C4CC E92D401E
0207C4D0 FAFE1F8E
D2000000 00000000
```

**Comment by the4anoni** [comment]
Code works fine.
Thanks :)
