### ISSUE TITLE
Code Whitescreens 

### ISSUE THREAD

**Issue by arandombro** [Prof9/WfcReplay#18]
I've been trying to get the code for Megaman Starforce 2: Zerker x Saurian, and no matter what I do, the game whitescreens upon booting. For reference, I'm running a retail copy of the game on an original DS with an AR DSI.

**Comment by Prof9** [comment]
Are you sure you're using the correct code? The following seems to work fine on No$gba and DeSmuME:

::Bypass HTTPS v0.6 for [YRWE] MSF2_Z_VS_S
52093740 EE070F90
E2000074 00000048
CA02A20D 58CC4B0B
D105429C 785C185B
3301701C D1FA4224
00A45E14 3202D005
D3EF1909 881403A1
4778E7F9 EE070F90
E8BD801E 2F2F3A73
D2DF8791 0009000A
0012006E 0000015E
02093740 E92D401E
02093744 FAFDB24A
D2000000 00000000

**Comment by chardrich** [comment]
Also in Professor Layton and the Curious Village (U)

**Comment by PokeAcer549** [comment]
31020 is a DLS1 error.

**Comment by Prof9** [comment]
@chardrich It looks like you are using DeSmuME r3947. Codes generated by WfcReplay will only work on DeSmuME r5047 or later, this is a problem on DeSmuME's end. You will have to use WfcPatcher in your scenario.

I'm going to close this issue for now as it's going off topic and the original poster hasn't replied in almost a year.
