### ISSUE TITLE
Error with generating code for Beyblade Metal Masters !!!

### ISSUE THREAD

**Issue by the4anoni** [Prof9/wfcreplay#19]
When I want generate code it says 
''Finishes analysing ROM
 No HTTPs URLs to patch were found.''
Please fix this !!!

**Comment by Prof9** [comment]
Although the cover features the Nintendo Wi-Fi Connection logo, this game doesn't actually have any online functionality. [(source)](http://www.nintendoworldreport.com/review/28930/beyblade-metal-masters-nintendo-ds) So it's not surprising that no URLs would be found.
