### ISSUE TITLE
Blackscreen (logo shine visible) on Kousoku Card Battle: Card Hero

### ISSUE THREAD

**Issue by PRIZZA** [Prof9/wfcreplay#22]
Bottom screen displays fine but the top screen is black, which the logo shine effect showing occasionally. MD5 checksum of: 921c58cfd2832369d19aa905eff104e9

What exactly causes this blackscreen error? Any help is greatly appreciated!

**Comment by Prof9** [comment]
What are you trying to run this on? From a brief emulator test, I got the problem you described on an old version of DeSmuME, but on the latest No$gba and DeSmuME dev build it was not present.

**Comment by PRIZZA** [comment]
Testing with DeSmuME_wifi_r4484 so I could attempt a WiFi connection. Do you know what may cause the blackscreen? I also have the same problem on DS hardware.

**Comment by Prof9** [comment]
That's good to hear, but, it shouldn't suddenly work by running it through WfcReplay multiple times... Was the final code that got generated any different from earlier codes?
