### ISSUE TITLE
Running HTTPS code via NitroHax fails

### ISSUE THREAD

**Issue by PokeAcer549** [Prof9/WfcReplay#24]
Using the HTTPS bypass code on Pokemon Platinum and Pearl (EUR) fails on @shutterbug2000's NitroHax copy.

**Comment by Prof9** [comment]
I have just tested and was able to log into the GTS perfectly fine on Pokémon Platinum and Pearl (EUR) with a WfcReplay code generated from the latest version, using akmenu on my Gateway blue card with an unpatched ROM. Check your process or take it up with the NitroHax developer.

**Comment by PokeAcer549** [comment]
I dumped Platinum via Decrypt9 (trimmed) and generated the AR code. I then added it to my cheat.xml and attempted to use it.
