### ISSUE TITLE
Armhook 9 error  (Bug)

### ISSUE THREAD

**Issue by meegs1089** [Prof9/WfcReplay#26]
Getting a fatal error cant find arm hook 9 using the newest version of Wfc Replay. Tested on Windows 7 and 10. Dragging Rom onto exe. flashes the command prompt for half a second and then closes. Nothing happens and no text file is produced. I had to time a screenshot to even read the error.

**Comment by Prof9** [comment]
You could start by filing a proper bug report.

**Comment by meegs1089** [comment]
Sorry new here. Looking for a place to submit one. On mobile device currently might have to try when I get home.

**Comment by meegs1089** [comment]
OK getting a fatal error cant find arm hook 9 using the newest version of Wfc Replay. Tested on Windows 7 and 10. Dragging Rom onto exe. flashes the command prompt for half a second and then closes. Nothing happens and no text file is produced. I had to time a screenshot to even read the error.

**Comment by meegs1089** [comment]
My initial comment apparently got cut off. (was using a mobile device) that is why OS info and such was missing. New here so not sure if a user can even add a label but if there is anything else I should do/include please let me know.

**Comment by Prof9** [comment]
How about some useful information?

I've just added a list that might be helpful [here](https://github.com/Prof9/WfcReplay/blob/master/CONTRIBUTING.md).

**Comment by meegs1089** [comment]
I solved the issue myself. A simple description of the information you were looking for would have been appreciated. Thanks anyway.
